name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '2.2.103', '3.0', '3.1.x' ]

    steps:
    - name: Install dependencies
      working-directory: ./Shop/Shop.Tests
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Shop/Shop.Tests

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./Shop/Shop.Tests
